# encoding: UTF-8

pg_ver = input('pg_version')

pg_dba = input('pg_dba')

pg_dba_password = input('pg_dba_password')

pg_db = input('pg_db')

pg_host = input('pg_host')

pg_timezone = input('pg_timezone')

control	'V-233532' do
	title	"PostgreSQL must record time stamps, in audit records and application data that can be mapped to 
	Coordinated Universal Time (UTC, formerly GMT)."
	desc	"If time stamps are not consistently applied and there is no common time reference, it is difficult to 
	perform forensic analysis.

Time stamps generated by PostgreSQL must include date and time. Time is commonly expressed in UTC, a modern 
continuation of GMT, or local time with an offset from UTC."
	desc	'rationale', ''
	desc	'check', "When a PostgreSQL cluster is initialized using initdb, the PostgreSQL cluster will be 
	configured to use the same time zone as the target server. 

As the database administrator (shown here as \"postgres\"), check the current log_timezone setting by running 
the following SQL:

$ sudo su - postgres
$ psql -c \"SHOW log_timezone\"

log_timezone
--------------
UTC
(1 row)

If log_timezone is not set to the desired time zone, this is a finding."
	desc	'fix', "Note: The following instructions use the PGDATA and PGVER environment variables. See 
	supplementary content APPENDIX-F for instructions on configuring PGDATA and APPENDIX-H for PGVER.

To change log_timezone in postgresql.conf to use a different time zone for logs, as the database administrator 
(shown here as \"postgres\"), run the following:

$ sudo su - postgres
$ vi ${PGDATA?}/postgresql.conf
log_timezone='UTC'

Next, restart the database:

$ sudo systemctl reload postgresql-${PGVER?}"
	impact 0.5
	tag severity: 'medium'
	tag gtitle: nil
	tag gid: nil
	tag rid: nil
	tag stig_id: nil
	tag fix_id: nil
	tag cci: nil
	tag nist: nil

	sql = postgres_session(pg_dba, pg_dba_password, pg_host, input('pg_port'))

	describe sql.query('SHOW log_timezone;', [pg_db]) do
	  its('output') { should eq pg_timezone }
	end
  end

